version: '3'

services:
  nginx-builder:
    container_name: nginx-builder
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: 'airdb/nginx-builer:latest'
    working_dir: /srv
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./lua:/etc/lua/
      - ./:/srv
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:80
  nginx:
    container_name: nginx
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.release
    image: 'airdb/nginx:latest'
    working_dir: /srv
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./lua/resty:/etc/lua/resty
      - ./:/srv
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8443:443
