version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'nginx:latest'
    volumes:
      - ./:/srv
    ports:
      - "8443:8443"
    environment:
      - env=dev
    container_name: nginx
  certbot:
    build:
      context: .
      dockerfile: ./Dockerfile.certbot
    image: 'certbot:latest'
    volumes:
      - ./:/srv/certbot
      - /srv/letsencrypt:/etc/letsencrypt
      - .dnspod.ini:/srv/dnspod.ini
    environment:
      - env=dev
    container_name: certbot
